### ISSUE TITLE
Switch to TextAPI 2.0

### ISSUE THREAD

**Issue by TheLuca98** [heyimblake/FunEffects#1]
I recommend switching to TextAPI 2.0 (Maven version: `1.8.8-R2.0`) since the old releases are deprecated. Also the new ones have a less strict license.

**Comment by heyimblake** [comment]
I'll switch to it when I have access to my computer +1. Thanks for opening an issue.

**Comment by heyimblake** [comment]
Done, will update the repo when I have more to offer :) Going ahead and closing this.

**Comment by heyimblake** [comment]
I'm late on this, but this was resolved with this commit https://github.com/heyimblake/FunEffects/commit/4ed3c01fb758ad0350bb741cce082272c50e682e
